# Generated by Django 3.2 on 2022-11-12 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_auto_20221112_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='marcas',
            new_name='marca',
        ),
    ]
