# Generated by Django 3.2 on 2022-11-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_rename_marcas_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_actual',
            field=models.PositiveIntegerField(default=1, verbose_name='Existencias disponibles del producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=1, verbose_name='Existencias minimas del producto'),
            preserve_default=False,
        ),
    ]
