# Generated by Django 3.2 on 2022-11-18 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0004_auto_20221118_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='existencias',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
