# Generated by Django 3.2 on 2022-11-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del cliente')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido del cliente')),
                ('telefono', models.IntegerField(verbose_name='Telefono del cliente')),
                ('dni', models.IntegerField(max_length=50, verbose_name='Dni del cliente')),
                ('carrito', models.ManyToManyField(to='Producto.Producto')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
