# Generated by Django 3.2 on 2022-11-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(verbose_name='Dni del cliente'),
        ),
    ]
