# Generated by Django 3.2 on 2022-11-18 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_rename_marcas_producto_marca'),
        ('Cliente', '0002_alter_cliente_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='carrito',
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrito', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.producto')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='carrito',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Cliente.carrito'),
            preserve_default=False,
        ),
    ]
