# Generated by Django 3.2 on 2022-11-18 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_rename_marcas_producto_marca'),
        ('Cliente', '0003_auto_20221118_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='carrito',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.producto'),
        ),
    ]
